### ISSUE TITLE
How do I build a Schema out of a Pydantic field?

### ISSUE THREAD

**Issue by iamgodot** [mike-oakley/openapi-pydantic#24]
The schema is to be used in constructing a Parameter for parsing of query parameters.

**Comment by iamgodot** [comment]
> Hi @iamgodot - apologies for the slow reply - i'm not sure exactly what you're asking here, but there are a few examples on the ReadMe [here](https://github.com/mike-oakley/openapi-pydantic#use-pydantic-classes-as-schema) which might help. Otherwise some more context of what you're having difficulty with would be helpful - thanks!

Thank you, I'll look it up and close this issue for now.

**Comment by Machine-Maker** [comment]
I too would like to know how to do this. If I have a pydantic model that gets created from a query_params dictionary, how can I turn that model into query parameters in an openapi schema? In other words, how can I turn a pydantic FieldInfo object into a openapi_pyantic Parameter object?
