### ISSUE TITLE
Handling lists / TypeAdapter

### ISSUE THREAD

**Issue by gberaudo** [mike-oakley/openapi-pydantic#33]
I want to return a special kind of JSON: a bare list of objects:

```json
["tour1", "tour2", ...]
```

Pydantic provides the [TypeAdapter](https://docs.pydantic.dev/latest/concepts/type_adapter/) to directly parse / serialize primitive types, and notably lists.

Unfortunately, using such adapter does not produces a class so it is not possible to use it directly with openapi-pydantic.

```py
# with PDCListTourOrRecordedTrack = TypeAdapter(list[Tour | Recorded])
# we get an error since that does not inherit from `BaseModel`
"schema": PydanticSchema(schema_class=PDCListTourOrRecordedTrack, enum=None),
```

Is this use case handled by openapi-pydantic?

**Comment by jcklie** [comment]
You could try to use root models [1].

[1]: https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types

**Comment by mike-oakley** [comment]
Hey @gberaudo - yep currently `schema_class` expects a type which has a base of `BaseModel` from pydantic so type adapters wouldn't work. As @jcklie suggested, you could try to use a root model for this use case as it should then conform to the expected interface?
